import Image from "next/image";

const services = [["01", "Sinalização viária", "Pintura e implantação de sinalização horizontal para vias urbanas, rodovias e áreas de circulação."], ["02", "Placas e sinalização vertical", "Soluções de orientação, regulamentação e segurança para obras, empreendimentos e espaços públicos."], ["03", "Projetos e execução", "Atendimento técnico desde o levantamento da demanda até a entrega da sinalização implantada."]];
const audiences = [["Setor público", "Câmaras, municípios e prefeituras com demandas de mobilidade, segurança e organização urbana."], ["Construção civil", "Empreiteiras e construtoras que precisam sinalizar obras, acessos e novos empreendimentos."], ["Propriedades privadas", "Condomínios, empresas e particulares que valorizam orientação clara e circulação segura."]];

export default function Home() { return <main>
  <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
  <header className="site-header"><a className="brand" href="#inicio" aria-label="GO Sinalização — início"><Image className="brand-logo" src="/images/go-sinalizacao-transparent.png" alt="GO Sinalização" width={150} height={100} priority /></a><nav aria-label="Navegação principal"><a href="#solucoes">Soluções</a><a href="#atendimento">Atendimento</a><a href="#empresa">A empresa</a></nav><a className="header-cta" href="#contato">Solicitar orçamento <span aria-hidden="true">↗</span></a></header>
  <section id="inicio" className="hero" aria-labelledby="hero-title"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><p className="eyebrow"><span /> Sinalização que orienta e protege</p><h1 id="hero-title">Segurança para<br /><em>cada caminho.</em></h1><p className="hero-text">Projetos e soluções em sinalização para cidades, obras e espaços que precisam funcionar melhor.</p><div className="hero-actions"><a className="button button-orange" href="#contato">Fale com nossa equipe <span aria-hidden="true">→</span></a><a className="text-link light" href="#solucoes">Conheça as soluções <span aria-hidden="true">↓</span></a></div></div><div className="hero-art"><Image src="/images/rodovia.jpg" alt="Rodovia com sinalização horizontal executada" fill priority sizes="(max-width: 800px) 280px, 35vw" /><div className="hero-photo-shade" /><div className="art-caption"><span>GO</span><p>Precisão técnica<br />em cada entrega.</p></div></div><div className="hero-footer"><span>APARECIDA DE GOIÂNIA · GO</span><span>DA PRIMEIRA DEMANDA ATÉ A ENTREGA</span></div></section>
  <section id="conteudo" className="intro section-pad"><p className="section-number">01 — O QUE FAZEMOS</p><div className="intro-layout"><h2>Mais clareza.<br />Mais <em>segurança.</em></h2><div><p>Transformamos necessidades de circulação e orientação em sinalização bem executada — com diálogo técnico, planejamento e compromisso com cada detalhe.</p><a className="text-link dark" href="#empresa">Conheça a GO Sinalização <span aria-hidden="true">→</span></a></div></div></section>
  <section id="solucoes" className="solutions section-pad" aria-labelledby="solucoes-title"><div className="section-heading"><p className="section-number">02 — SOLUÇÕES</p><h2 id="solucoes-title">A solução certa<br />para cada <em>trajeto.</em></h2></div><div className="service-list">{services.map(([number,title,description]) => <article className="service-card" key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div><b aria-hidden="true">↗</b></article>)}</div></section>
  <section id="atendimento" className="audiences section-pad"><div className="audience-intro"><p className="section-number">03 — PARA QUEM</p><h2>Parceria para<br />quem faz a cidade<br /><em>acontecer.</em></h2></div><div className="audience-list">{audiences.map(([title,description],index) => <article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
  <section className="process" aria-label="Como funciona nosso atendimento"><div className="process-word" aria-hidden="true">GO</div><div className="process-content"><p className="section-number">UM PROCESSO CLARO</p><h2>Da demanda<br />à <em>solução.</em></h2><ol><li><span>01</span> Entendemos o contexto</li><li><span>02</span> Planejamos a melhor solução</li><li><span>03</span> Executamos com cuidado técnico</li></ol></div></section>
  <section className="portfolio section-pad" aria-labelledby="portfolio-title"><div className="portfolio-heading"><p className="section-number">04 — PORTFÓLIO</p><h2 id="portfolio-title">Trabalho que se vê<br />em cada <em>detalhe.</em></h2></div><div className="portfolio-grid"><figure className="portfolio-main"><Image src="/images/placa-rua.jpg" alt="Placas de identificação de ruas instaladas" fill sizes="(max-width: 800px) 100vw, 48vw" /><figcaption>Sinalização vertical urbana</figcaption></figure><figure><Image src="/images/pintura-pare.jpg" alt="Pintura de parada em via" fill sizes="(max-width: 800px) 50vw, 24vw" /><figcaption>Sinalização horizontal</figcaption></figure><figure><Image src="/images/equipamentos.jpg" alt="Equipamentos para sinalização de obras" fill sizes="(max-width: 800px) 50vw, 24vw" /><figcaption>Estrutura para obras</figcaption></figure><figure className="portfolio-wide"><Image src="/images/sede.jpg" alt="Fachada da sede da GO Sinalização" fill sizes="100vw" /><figcaption>Atendimento local em Aparecida de Goiânia</figcaption></figure></div></section>
  <section id="empresa" className="about section-pad"><p className="section-number">05 — SOBRE A GO</p><div><h2>Sinalizar é<br /><em>cuidar.</em></h2><p>A GO Sinalização atua para tornar os espaços mais seguros, legíveis e preparados para o movimento de pessoas e veículos. Unimos experiência prática e atendimento próximo para entregar sinalização com propósito.</p></div></section>
  <section id="contato" className="contact" aria-labelledby="contato-title"><div><p className="eyebrow"><span /> Vamos conversar</p><h2 id="contato-title">Seu projeto começa<br />com uma boa <em>conversa.</em></h2><p>Conte o que sua cidade, obra ou propriedade precisa sinalizar. Nossa equipe está pronta para entender a demanda.</p></div><div className="contact-card"><p>ATENDIMENTO</p><a href="tel:+556232050307">(62) 3205-0307 <span aria-hidden="true">↗</span></a><address>Av. W, Q. 83 — Mansões Paraíso<br />Aparecida de Goiânia — GO</address><small>Dados de contato e materiais visuais serão atualizados na versão final.</small></div></section>
  <footer><a className="brand" href="#inicio"><Image className="brand-logo" src="/images/go-sinalizacao-transparent.png" alt="GO Sinalização" width={136} height={91} /></a><p>© 2026 GO Sinalização. Todos os direitos reservados.</p><a href="#inicio">Voltar ao topo ↑</a></footer>
</main>; }
